server:
  #端口号
  port: 8990
  #项目名，如果不设定，默认是 /
 # context-path: /vote

 #http://www.cnblogs.com/bigdataZJ/p/springboot-log.html
logging:
  ##日志存储地址
  file: /usr/project/logs/reptiles.log
  level:
#   sun: warn
   orgSpringframework: info
 #  root: debug
   com.reptile: INFO

#logging.pattern.console=%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#logging.pattern.file=%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
info:
  name: "入门案例"

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.reptile.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configLocation: classpath:/mybatis/mybatis-config.xml

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.winter.model  # 注意：对应实体类的路径
#  configLocation: classpath:mybatis-config.xml



#开发配置
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/test
#    url: jdbc:mysql://106.2.11.94:3306/zz_wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    url: jdbc:mysql://106.2.13.148:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123&456
    driver-class-name: com.mysql.cj.jdbc.Driver
 # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      test-while-idle: true
      initial-size: 24
      min-idle: 10


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql





WEB_URL: http://weixin.sogou.com/weixin
#WEB_CONDITION: usip=&ft=&tsn=2&et=&interation=&type=2&wxid=&ie=utf8
WEB_CONDITION: type=2&ie=utf8&tsn=5&ft=startTime&et=endTime&interation=&wxid=&usip=
#ARTICLE_COOKIE: ABTEST=0|1546224997|v1; SNUID=D7F82009BDB8C3F631047C4FBEC01103; IPLOC=CN3301; SUID=6A459DB74018960A000000005C298565; SUID=6A459DB72C18960A000000005C298565; weixinIndexVisited=1; SUV=00C57A6CB79D456A5C298566A6193839; JSESSIONID=aaatctzYX5-bpcLb0JcDw; ppinf=5|1546236551|1547446151|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToxODolRTQlQkUlOUQlRTYlOTclQTd8Y3J0OjEwOjE1NDYyMzY1NTF8cmVmbmljazoxODolRTQlQkUlOUQlRTYlOTclQTd8dXNlcmlkOjQ0Om85dDJsdU1kbmsxVVdseWNjQ043Wkk5cGFaa1lAd2VpeGluLnNvaHUuY29tfA; pprdig=iNIOsCiJfFLgjpbivXQbylbOA68X6uTsgaUh7nMnpDmQ12EWZ-RSU6MQjcxrPCPbYGIUxDY4kMj2ZKXVtFnz6amvpJuwmyB0VczoGBpNsjfLdRRMpX2gJ1bwU17JXx22uS2SoLtJ_JfbyIJK_-beDOCmgejS3hzCqCEApEQZcug; sgid=03-36145051-AVwpsoeJ8uM146HB3smBafo; sct=6; ppmdig=1546323823000000f8a91af3cb8296e4c00f0a3a008bf574
#WEB_COOKIE: ABTEST=0|1546224997|v1; SNUID=D7F82009BDB8C3F631047C4FBEC01103; IPLOC=CN3301; SUID=6A459DB74018960A000000005C298565; SUID=6A459DB72C18960A000000005C298565; weixinIndexVisited=1; SUV=00C57A6CB79D456A5C298566A6193839; JSESSIONID=aaatctzYX5-bpcLb0JcDw; ppinf=5|1546236551|1547446151|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToxODolRTQlQkUlOUQlRTYlOTclQTd8Y3J0OjEwOjE1NDYyMzY1NTF8cmVmbmljazoxODolRTQlQkUlOUQlRTYlOTclQTd8dXNlcmlkOjQ0Om85dDJsdU1kbmsxVVdseWNjQ043Wkk5cGFaa1lAd2VpeGluLnNvaHUuY29tfA; pprdig=iNIOsCiJfFLgjpbivXQbylbOA68X6uTsgaUh7nMnpDmQ12EWZ-RSU6MQjcxrPCPbYGIUxDY4kMj2ZKXVtFnz6amvpJuwmyB0VczoGBpNsjfLdRRMpX2gJ1bwU17JXx22uS2SoLtJ_JfbyIJK_-beDOCmgejS3hzCqCEApEQZcug; sgid=03-36145051-AVwpsoeJ8uM146HB3smBafo; sct=6; ppmdig=1546323823000000f8a91af3cb8296e4c00f0a3a008bf574

#ARTICLE_COOKIE: ABTEST=0|1545024878|v1; SNUID=C07831A37A7C074B59775B087AC6ABBE; IPLOC=CN3310; SUID=BA014BDA4018960A000000005C17356E; SUID=BA014BDA3118960A000000005C17356F; weixinIndexVisited=1; SUV=00503DF0DA4B01BA5C173572C5D45569; sct=2; ppinf=5|1545028628|1546238228|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToyNzolRTYlOUQlQTglRTYlOTklOTMlRTUlODclQTF8Y3J0OjEwOjE1NDUwMjg2Mjh8cmVmbmljazoyNzolRTYlOUQlQTglRTYlOTklOTMlRTUlODclQTF8dXNlcmlkOjQ0Om85dDJsdVAzc2U5TkpOOGxjRy02dXAzeUNnLVFAd2VpeGluLnNvaHUuY29tfA; pprdig=RMzxbGWcI_xHEu8sDS2c71P3WLjGAqP9lPZ4QYSojjL8ApC7FcHz02QYln0ioQPixrKptNR4dFhToD7SdKHK21BWucwe8s2hc3pWgU7GW-NYGRYsPvhDjQbslsQ94v5c1YqBHfttu47aIcOfDC6kUlB2908byjDTQubBj06tZ3c; sgid=25-38031237-AVwXRBQIiae6L1GiaXlpiaZ6VI; ppmdig=15450327290000003a4e7e90d687e2bde7f92fa99723f7e1; JSESSIONID=aaad8ORQVzqvg-_cAcaDw
#WEB_COOKIE: ABTEST=0|1545024878|v1; SNUID=C07831A37A7C074B59775B087AC6ABBE; IPLOC=CN3310; SUID=BA014BDA4018960A000000005C17356E; SUID=BA014BDA3118960A000000005C17356F; weixinIndexVisited=1; SUV=00503DF0DA4B01BA5C173572C5D45569; sct=2; ppinf=5|1545028628|1546238228|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToyNzolRTYlOUQlQTglRTYlOTklOTMlRTUlODclQTF8Y3J0OjEwOjE1NDUwMjg2Mjh8cmVmbmljazoyNzolRTYlOUQlQTglRTYlOTklOTMlRTUlODclQTF8dXNlcmlkOjQ0Om85dDJsdVAzc2U5TkpOOGxjRy02dXAzeUNnLVFAd2VpeGluLnNvaHUuY29tfA; pprdig=RMzxbGWcI_xHEu8sDS2c71P3WLjGAqP9lPZ4QYSojjL8ApC7FcHz02QYln0ioQPixrKptNR4dFhToD7SdKHK21BWucwe8s2hc3pWgU7GW-NYGRYsPvhDjQbslsQ94v5c1YqBHfttu47aIcOfDC6kUlB2908byjDTQubBj06tZ3c; sgid=25-38031237-AVwXRBQIiae6L1GiaXlpiaZ6VI; ppmdig=15450327290000003a4e7e90d687e2bde7f92fa99723f7e1; JSESSIONID=aaad8ORQVzqvg-_cAcaDw
ARTICLE_COOKIE: _ga=GA1.2.1718690277.1547003018; pgv_pvi=4500842496; RK=ln4h1vedW1; ptcz=d4b6422eb8e77a0ee00d82c21b2c1e12942c544bc0d3151990bbc90abcf58fdb; ua_id=5ZUMipdAgNgFIC2lAAAAAEeyaqhBDFLivvRpseStKNQ=; xid=bba4cd5f7fc6f2948339bd8ffad50fd0; mm_lang=zh_CN; pgv_pvid=4410180154; ts_uid=2295809938; rewardsn=; wxtokenkey=777
WEB_COOKIE: CXID=81945D65328D26038F38D9BAB73169FB; weixinIndexVisited=1; SUV=00983DF2B781ECDA5C47D8B4AAF85422; ad=qkllllllll2tBunJlllllVeuYc6lllllHc47Lkllll9lllllRCxlw@@@@@@@@@@@; SUID=CB669CB73765860A5C31ADC8000C97B9; ABTEST=3|1551177707|v1; sw_uuid=3558220219; ssuid=6886420000; SNUID=EA510495504ACC0277E18ADA50F9C9FC; IPLOC=CN3310; td_cookie=2816915278; sct=21; JSESSIONID=aaaYEFSdje41s5xjg3ZKw; ppinf=5|1551783949|1552993549|dHJ1c3Q6MToxfGNsaWVudGlkOjQ6MjAxN3x1bmlxbmFtZToxODolRTQlQkUlOUQlRTYlOTclQTd8Y3J0OjEwOjE1NTE3ODM5NDl8cmVmbmljazoxODolRTQlQkUlOUQlRTYlOTclQTd8dXNlcmlkOjQ0Om85dDJsdU1kbmsxVVdseWNjQ043Wkk5cGFaa1lAd2VpeGluLnNvaHUuY29tfA; pprdig=GADrtC5Lwozhqh44EKQfMisFjoTxOHgIoKAWeNiJwvg-CnAA5_tlSTn5aEtDv_rf1jnGSv-Cia77BHXOebCe4tu-4BKLBubG9Tu6P94wmXLNHKJathh77YqYn7Bna6lrNQCCljpcL6ghoRSJJnIe7CASn0ko715nTLh3GKv78Vw; sgid=03-36145051-AVxibWA0eTlIImlxiaibS1ticvs; ppmdig=15517839490000005a60d16d3f3a99805716ccfd14eb456e

USER_AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.23 Safari/537.36

DATA_NUM: 15

KEYWORK_NUM: 10
INTERVAL_DAY: 27
#插入文章
TASK_TIME: 0 0/2 * * * ?
#文章概要扫描
ArticleTask: 0 0 0/1 * * ?
#定时更新ip
setIpPost: 0 0 5,9,16,23 * * ?
#文章类型分类ip地址
articlePath: http://106.2.13.136:8889/

#文章摘要ip地址
abstractPath: http://106.2.13.136:8080/


#文章推送到主服务器上
#postPath: http://106.2.13.136:7903/
postPath: http://localhost:7903/


#查询文章分类的页数
rasterProp:
  path: ..\zz_reptile\src\main\resources\filelist.properties
   # path: D:\reptiles\filelist.properties


